a = []
f1 = input("Add the Name of Fruit")
a.append(f1)
f2 = input("Add the Name of Fruit")
a.append(f2)
f3 = input("Add the Name of Fruit")
a.append(f3)
f4 = input("Add the Name of Fruit")
a.append(f4)
f5 = input("Add the Name of Fruit")
a.append(f5)
f6 = input("Add the Name of Fruit")
a.append(f6)
f7 = input("Add the Name of Fruit")
a.append(f7)
print("Final List of Fruit",a)